//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrantAWish.Database_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Admin1 = new HashSet<Admin>();
            this.Wishes = new HashSet<Wishes>();
        }
    
        public int adminID { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string contact_Number { get; set; }
        public Nullable<int> addedby { get; set; }
    
        public virtual ICollection<Admin> Admin1 { get; set; }
        public virtual Admin Admin2 { get; set; }
        public virtual ICollection<Wishes> Wishes { get; set; }
    }
}
