//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrantAWish.Database_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishes
    {
        public int wishId { get; set; }
        public string wisherName { get; set; }
        public int wisherAge { get; set; }
        public string wisherGender { get; set; }
        public string wish { get; set; }
        public System.DateTime wishDate { get; set; }
        public int wishStatus { get; set; }
        public Nullable<int> addedBy { get; set; }
        public Nullable<long> grantedBy { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual User User { get; set; }
    }
}
